### ISSUE TITLE
refinedet_test.py

### ISSUE THREAD

**Issue by china56321** [wj1tr0y/RefineDet#3]
test_set = 'coco_2017_val' 
  coco_path = 'models/ResNet/coco/refinedet_resnet101_512x512/'

where should i point at the coco_path? the path of  JPEGImages ?or lmdb ?

**Comment by wj1tr0y** [comment]
coco_path is where you store models.
In order to create your own lmdb, you should modify following files.
data/coco/create_data.sh	
data/coco/create_list.py
data/coco/labelmap_coco.prototxt
data/coco/labels.txt
and it will automaticlly generate a soft link in 'examples' folder, you just need pass the dataset name to test_set.
